### ISSUE TITLE
VQO data source

### ISSUE THREAD

**Issue by smnorris** [bcgov/designatedlands#24]
VQO data is available in BCGW, but the file size exceeds the capacity of the download service.

As a stopgap, the data is currently pulled from a manual extract posted to my web server:
http://www.hillcrestgeo.ca/outgoing/conservationlands/VLI.gdb.zip

**Comment by ateucher** [comment]
@smnorris can we close this as at least a partial duplicate of #43?

**Comment by smnorris** [comment]
I'll close #43. 
It looks like DWDS remains the only resource listed at https://catalogue.data.gov.bc.ca/dataset/visual-landscape-inventory so some kind of alternative method is needed for downloading the data.  Posting to gh is probably best, I think I know a kludge to get around the error in #43.

**Comment by smnorris** [comment]
VLI data now downloads fine via `bcdata`/ DWDS, perhaps the max size has been upped.
