### ISSUE TITLE
Add name column to extracted data

### ISSUE THREAD

**Issue by smnorris** [bcgov/designatedlands#26]
Harvesting restrictions mapping requires that the feature name be retained in the cleaned tables.  (ie `PA_NAME` etc). 

The column to be retained can be noted by adding a `name_column_source` or similar to `sources.csv`. However, retaining this in the cleaned tables would require an additional `ST_Union`  when things get added to the output - there are overlapping features within individual sources (with different names).

Whether the name column is retained could perhaps be a switch in the `CONFIG` dict. Or it could be the default behaviour - it wouldn't change the conservationlands output, just the intermediate layers which are not currently used.

**Comment by ateucher** [comment]
@smnorris I think this is also done. Close?

**Comment by smnorris** [comment]
Yep
