### ISSUE TITLE
validate --out_table option in CLI

### ISSUE THREAD

**Issue by smnorris** [bcgov/designatedlands#46]
Supplying an `--out_table` option value with an upper case character will throw an error - all table names are lowercase. Clean the provided option value.

**Comment by ateucher** [comment]
@smnorris it looks like this is taken care of [here](https://github.com/bcgov/designatedlands/blob/v010/designatedlands/config.py#L25-L26)?

**Comment by smnorris** [comment]
fixed with https://github.com/bcgov/designatedlands/commit/8e21a1f9f733692e12eac0c200d5de6612f2fc8d#diff-344c4a5d843686ab8fa2556bfff25b5a
