### ISSUE TITLE
Change category for Forest Rec Sites layer

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/designatedlands#50]
Currently [Forest Rec Sites]( https://catalogue.data.gov.bc.ca/dataset/recreation-polygons) are included in the `03_Exclude_1_2_Activities` category. This designation category should be changed to  `04_Managed`.  Forest Rec Sites cover ~577,090 ha, about 0.61% of terrestrial land in B.C. This change will result in a small to no change in the provincial summaries of land designation totals for the 3 categories (Protected Lands, Resource Exclusion Areas, and Spatially Managed Areas), however may result in larger changes to category amounts at smaller spatial scales (e.g. ecoregions).

**Comment by smnorris** [comment]
Does it matter where this source falls in the hierarchy within `04_Managed` (with this addition, now #s 29-45) ?

**Comment by ateucher** [comment]
As they are all aggregated up at the category level, it doesn't really matter. But  at the top of `04_Managed` as you've done makes sense
