### ISSUE TITLE
Remove water when dumping to file

### ISSUE THREAD

**Issue by ateucher** [bcgov/designatedlands#54]
For dumping final file would just require an additional `WHERE` statement on `bc_boundary` field, but  `designatedlands_overlaps` table doesn't have that field, so will need to ensure it's there upstream

**Comment by ateucher** [comment]
Regardless, `designatedlands_overlaps` should have the `bc_boundary` field

**Comment by smnorris** [comment]
Just `designatedlands_overlaps` table should be dumped with marine removed? Or `designatedlands` as well?

**Comment by ateucher** [comment]
Both I think

**Comment by ateucher** [comment]
Actually, scratch that. the `_overlaps` file should have the `bc_boundary` field, but perhaps water should be retained in both for maximum flexibility for the user
