### ISSUE TITLE
config file path is hard coded

### ISSUE THREAD

**Issue by smnorris** [bcgov/designatedlands#59]
README notes that the tool will accept custom config files and `read_config` function accepts a path as an argument... but there is no actual mechanism for changing the path set here:
https://github.com/bcgov/designatedlands/blob/master/designatedlands/config.py#L44

**Comment by smnorris** [comment]
Note that this does not just mean the config file must be named `designatedlands.cfg`, it must also be located in the folder in which the module is loaded - the tool will bail if `designatedlands.cfg` does not exist in the current working directory.

**Comment by ateucher** [comment]
No longer an issue after #74
