### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by smnorris** [bcgov/designatedlands#6]
Tidy logging
- log download failures to file
- don't show the user all info level logging (ie `requests` starting new connection)

**Comment by ateucher** [comment]
@smnorris you've done a lot of work on logging. Can we close this too?

**Comment by smnorris** [comment]
There is a now structure for logging but logging to file didn't really help with development so this issue was neglected and I haven't checked that it is working.

**Comment by ateucher** [comment]
Ok, well we can leave it open, it's not part of the 0.1 milestone and not critical at this point

**Comment by smnorris** [comment]
Looks like this one can be closed now too.
