### ISSUE TITLE
bc boundary layer name

### ISSUE THREAD

**Issue by smnorris** [bcgov/designatedlands#60]
GeoBC now calls the BC Boundary layer `BC_Boundary_Terrestrial_Singlepart`
Modify `layer_in_file` key in `sources.csv` if re-running.

**Comment by ateucher** [comment]
The high resolution boundary has been published in the catalogue, should be able to get with `bcdata`

https://catalogue.data.gov.bc.ca/dataset/province-of-british-columbia-boundary-terrestrial

**Comment by smnorris** [comment]
Great news! 

It won't be available directly via Python `bcdata` as it just accesses the WFS/WCS.
But that doesn't matter - there is a url, that is just as good or better. ftp://ftp.geobc.gov.bc.ca/sections/outgoing/bmgs/BC_Boundary_Terrestrial/BC_Boundary_Terrestrial.gpkg.zip

**Comment by smnorris** [comment]
Presuming the posted GPKG/gdb are exactly the same, I'd probably just use the .gdb, it is smaller:
ftp://ftp.geobc.gov.bc.ca/sections/outgoing/bmgs/BC_Boundary_Terrestrial/BC_Boundary_Terrestrial.gdb.zip

**Comment by ateucher** [comment]
Excellent! I assume they should be the same

**Comment by smnorris** [comment]
I already noted this as fixed in the fork - but with this update, no manual downloads remain. https://github.com/smnorris/designatedlands/commit/8d90268e2c33b69d736c6a3580f94b06b0cd7269
