### ISSUE TITLE
simplify lostgis function inclusion

### ISSUE THREAD

**Issue by smnorris** [bcgov/designatedlands#66]
There are just three functions required.

Simply include the functions in this repository rather than installing via pgxn or the windows installation script.

**Comment by ateucher** [comment]
Sounds good to me - as long as the lostgis licence is compatible with Apache 2.

**Comment by ateucher** [comment]
Looks like lostgis is BSD 3-clause, which is not copyleft so should be fine to include.

**Comment by smnorris** [comment]
Yes, adding those should probably have been a separate commit 🤪

**Comment by ateucher** [comment]
No worries. 

Do you think we could include the lostgis functinos in a subfolder (`sql/lostgis/`)? Then put a copy of the BSD 3-Clause `LICENSE` file in that folder? Also in the license section in the main `README.md` state that those files are included from lostgis and distributed under the BSD 3-Clause license. I don't think there are hard and fast rules for how to properly include and license 3rd-party code, but I like to be as clear as possible...

**Comment by smnorris** [comment]
Good idea, will do.
