### ISSUE TITLE
priority_order 20 is duplicated in current designation source list

### ISSUE THREAD

**Issue by smnorris** [bcgov/designatedlands#76]

**Comment by smnorris** [comment]
Note that editing the `priority_order` column is a pain if excluding any sources, user has to remember that excluded sources do not get included in the numbering. If we retain the explicit priority order numbering, I'd consider removing excluded sources from the list entirely, putting them in some other file.

**Comment by ateucher** [comment]
closed by 906528a0e2fb3ba6087e73b3dd89c7b189602583
